### ISSUE TITLE
Build image with private repository (Bitbucket Cloud)

### ISSUE THREAD

**Issue by aca-support** [pivotal/kpack#1002]
Hi,

I'm new to kpack. I have downloaded and deployed everything to the cluster. I have also created successfully an Image and deployed to my personal Docker Hub registry.

Next step was, to change the Git URL from the sample (tutorial) git repository to our Bitbucket Cloud repository.
I deployed Secret with my username and password, and changed the Git URL in the Image resource.

Secret
```
apiVersion: v1
kind: Secret
metadata:
  name: basic-git-user-pass
  namespace: kpack
  annotations:
    kpack.io/git: https://bitbucket.org
type: kubernetes.io/basic-auth
stringData:
  username: username
  password: xxxx
---
```

Image
```
apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: tutorial-bitbucket-image
  namespace: kpack
spec:
  tag: ugurakkar/testing
  serviceAccountName: tutorial-service-account
  builder:
    name: my-builder
    kind: Builder
  source:
    git:
      url: https://bitbucket.org/xxx/xxx-kpack-tutorials.git
      revision: tst
```

ServiceAccount
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tutorial-service-account
  namespace: kpack
secrets:
  - name: tutorial-registry-credentials
  - name: basic-git-user-pass
```

Logs from building image
```
Build reason(s): CONFIG
CONFIG:
	resources: {}
	- source: {}
	+ source:
	+   git:
	+     revision: tst
	+     url: https://bitbucket.org/xxx/xxx-kpack-tutorials.git
Loading secret for "https://index.docker.io/v1/" from secret "tutorial-registry-credentials" at location "/var/build-secrets/tutorial-registry-credentials"
Loading cluster credential helpers
Cloning "https://bitbucket.org/xxx/xxx-kpack-tutorials.git" @ "tst"...
fetching remote: no credentials found for https://bitbucket.org/xxx/xxx-kpack-tutorials.git
```

Could you please help me with the private repository configuration?
