### ISSUE TITLE
Getting `UNAUTHORIZED: authentication required` when trying to setup builder

### ISSUE THREAD

**Issue by jim-junior** [pivotal/kpack#1031]
I have been following the `kpack` tutorial. but my images are not building and it seems the error is from the builder. I have followed the docs.
When i describe the builder see this at the end
```
status:
  conditions:
    - lastTransitionTime: '2022-09-09T16:24:17Z'
      message: >-
        POST
        https://index.docker.io/v2/jimjuniorb/kpbuilder/blobs/uploads/?from=cf-build-service-public%2Fkpack%2Flifecycle&mount=sha256%3A309e52899ba609589eb34b1e7687472d2d9183e2faf52d73fe34ea3618683e86&origin=REDACTED:
        UNAUTHORIZED: authentication required; [map[Action:pull Class:
        Name:jimjuniorb/kpbuilder Type:repository] map[Action:push Class:
        Name:jimjuniorb/kpbuilder Type:repository] map[Action:pull Class:
        Name:cf-build-service-public/kpack/lifecycle Type:repository]]
      status: 'False'
      type: Ready
  observedGeneration: 3
  stack: {}
```

These are my configuration files.

### secrets,yml 
```yml
apiVersion: v1
kind: Secret
metadata:
  name: docker-sec
  annotations:
    kpack.io/docker: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
stringData:
  username: jimjuniorb
  password: <MY-PASSWORD>
```

### serviceaccount.yml
```yml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack-sva
  namespace: default
secrets:
- name: docker-sec
imagePullSecrets:
- name: docker-sec
```

### clusterstore.yml
```yml
apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: default-store
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/java
  - image: gcr.io/paketo-buildpacks/nodejs
  - image: gcr.io/buildpacks/builder:v1
  - image: paketobuildpacks/builder:base
```

### clusterstack.yml
```yml
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: base-stack
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "paketobuildpacks/build:base-cnb"
  runImage:
    image: "paketobuildpacks/run:base-cnb"
```

### clusterbuilder.yml 
```yml
apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: default-builder
  namespace: default
spec:
  # Cluster service account
  serviceAccountRef:
    name: kpack-sva
    namespace: default
  # Builder tag
  tag: jimjuniorb/kpbuilder
  stack:
    name: base-stack
    kind: ClusterStack
  store:
    name: default-store
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/nodejs
  - group:
    - id: paketo-buildpacks/python
  - group:
    - id: paketo-buildpacks/go
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/ruby
```
### image.yml
```yml
apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: tutorial-image-1
  namespace: default
spec:
  tag: jimjuniorb/kpack-tutarial-image
  serviceAccountName: kpack-sva
  builder:
    name: default-builder
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/spring-projects/spring-petclinic
      revision: 82cb521d636b282340378d80a6307a08e3d4a4c4
```
