### ISSUE TITLE
new build is failed to be triggered by kpack-controller when previous build has somethind wrong

### ISSUE THREAD

**Issue by zhoufenqin** [pivotal/kpack#1089]
# Description
Kpack version: 0.7.2
After creating a cnb image with error env, the pod can't be triggered because the error configuration. But after correct the cnb image with correct env configuration, a new build can't be triggered too.

# Reproduce step
1. Create a build with error env
```
apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: default.test1-deployment
  namespace: build-service
spec:
  additionalTags:
  - xxxxxxx-default-test1-deployment:result-2
  build:
    env:
    - name: '{BP_JVM_VERSION:8}'  // Error env configuration
      value: ""
    ...
  builder:
    apiVersion: kpack.io/v1alpha2
    kind: Builder
    name: default.default.1
  ...
  source:
    blob:
      url: xxx
  tag: - xxxxxxx-default-test1-deployment:result
```
Then kpack-controller will report errors: 
```
{
   "level":"error",
   "ts":"2022-12-08T04:48:57.193459241Z",
   "logger":"controller",
   "caller":"controller/controller.go:566",
   "msg":"Reconcile error",
   "commit":"9343a26-dirty",
   "knative.dev/kind":"builds.kpack.io",
   "knative.dev/traceid":"9a908342-0d22-4e9a-a5c8-d0ff5afa199a",
   "knative.dev/key":"build-service/default.test1-deployment-build-1",
   "duration":0.324729574,
   "error":"Pod \"default.test1-deployment-build-1-build-pod\" is invalid: spec.initContainers[0].env[2].name: Invalid value: \"PLATFORM_ENV_{BP_JVM_VERSION:8}\": a valid environment variable name must consist of alphabetic characters, digits, '_', '-', or '.', and must not start with a digit (e.g. 'my.env-name',  or 'MY_ENV.NAME',  or 'MyEnvName1', regex used for validation is '[-._a-zA-Z][-._a-zA-Z0-9]*')",
   "stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20220816153547-f78a00694307/controller/controller.go:566\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20220816153547-f78a00694307/controller/controller.go:543\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20220816153547-f78a00694307/controller/controller.go:491"
}
```

2. patch the cnb image with correct configuration
```
apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: default.test1-deployment
  namespace: build-service
spec:
  additionalTags:
  - xxxxxxx-default-test1-deployment:result-3
  build:
    env:
    - name: BP_JVM_VERSION  // correct env configuration
      value: 8.*
    ...
  builder:
    apiVersion: kpack.io/v1alpha2
    kind: Builder
    name: default.default.1
  ...
  source:
    blob:
      url: xxx
  tag: - xxxxxxx-default-test1-deployment:result
```

The new build can't be triggered, there is still only previous build resource exist and kpack will continues report the previous build failed information
![image](https://user-images.githubusercontent.com/8765864/206362663-0ada7f7e-3e7b-4078-b750-0efcf4898e0b.png)

Why update the cnbimage can't trigger a new build? is it a bug?
