### ISSUE TITLE
exec /cnb/process/controller: no such file or directory

### ISSUE THREAD

**Issue by okoklets** [pivotal/kpack#1192]
when i install kpack from the yaml using kubectl apply --filename like so:

kubectl apply --filename https://github.com/pivotal/kpack/releases/download/v0.9.4/release-0.9.4.yaml

the controller and webhook pods go into CrashLoopBackOff

and I get these errors in the log:

exec /cnb/process/controller: no such file or directory

for the controller, and:-

exec /cnb/process/webhook: no such file or directory

for the webhook.

steps to reproduce:  above (i have tried with version 0.10.1 as well)

/kind bug

**Comment by tomkennedy513** [comment]
Hi, We are not able to reproduce this. Can you share more info about the environment you are attempting to install in?

**Comment by pviraj59** [comment]
closing this issue.

**Comment by okoklets** [comment]
i believe it may have been because i was on aarch64 arm64 architechture.  sorry i never got back to you on this.  i would really like to see this working on arm64.

**Comment by dashaun** [comment]
@okoklets This works on MacOS with Apple Silicon ARM64 because of the built in emulation.

In order to get Kpack working on other ARM64 (Raspberry Pi) I added the emulation to all of the nodes with a DaemonSet:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: binfmt
  labels:
    app: binfmt-setup
spec:
  selector:
    matchLabels:
      name: binfmt
  template:
    metadata:
      labels:
        name: binfmt
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      initContainers:
        - name: binfmt
          image: tonistiigi/binfmt
          args: ["--install", "all"]
          securityContext:
            privileged: true
      containers:
        - name: pause
          image: arm64v8/alpine
          command: ["sleep","infinity"]
          resources:
            requests:
              memory: "1Mi"
              cpu: "1m"
```
> binfmt-daemonset.yaml

```bash
kubectl apply -f binfmt-daemonset.yaml
```
