### ISSUE TITLE
GitHub private repositories fail due to `unable to find any valid known_hosts file, set SSH_KNOWN_HOSTS env variable`

### ISSUE THREAD

**Issue by usiegj00** [pivotal/kpack#1230]
Kpack 0.11.0 [replaced git2go with go-git](#1159) and doing so GitHub private repositories fail due to this error:
`unable to fetch references for repository: unable to find any valid known_hosts file, set SSH_KNOWN_HOSTS env variable`

The same configuration works with kpack-0.9.4 without issue. This appears to be a regression due git2go -> go-git and may be caused by the handling of known_hosts in the context of the underlying SSH connection to GitHub's git repositories. 

In kpack-0.9.4, private repositories on GitHub required a secret that included GitHub's SSH public key(s). For example KNOWNHOSTS64 below would be `ssh-keyscan github.com` encoded base64. This requirement was pieced together from aged documentation references including #413. It is possible that this issue is from some unrelated misconfiguration we have, so we'd like this to be confirmed prior to giving this issue any more attention!

```
apiVersion: v1
data:
  known_hosts: KNOWNHOSTS64
  ssh-privatekey: PRIVATEKEY64
kind: Secret
metadata:
  annotations:
    kpack.io/git: git@github.com
```  

This has been tested by trying identical Image configurations on kpack-0.9.4 (working) and kpack-0.11.0 (not working).
