### ISSUE TITLE
Builder.Spec.Image does not support images with digest

### ISSUE THREAD

**Issue by matthewmcnew** [pivotal/kpack#128]
Currently, kpack cannot process builders with an image that includes a digest. 

```yaml
apiVersion: build.pivotal.io/v1alpha1
kind: Builder
metadata:
  name: sample-builder
spec:
  image: cloudfoundry/cnb:bionic@sha256:b100bb7ba4d9109146965dbba0c91784bef2789b4fca759f4e734d55ea89a6af
```
Will fail to successfully reconcile the builder. 

kpack controller logs:
```
a digest must contain exactly one '@' separator (e.g. registry/repository@digest) saw: cloudfoundry/cnb:bionic@sha256:b100bb7ba4d9109146965dbba0c91784bef2789b4fca759f4e734d55ea89a6af@sha256:b100bb7ba4d9109146965dbba0c91784bef2789b4fca759f4e734d55ea89a6af
creating digest reference
```
