### ISSUE TITLE
Add support Run Image mirrors

### ISSUE THREAD

**Issue by matthewmcnew** [pivotal/kpack#190]
Similar to: https://github.com/pivotal/kpack/issues/79.

Currently, the only way to utilize a run image mirror for a non dockerhub run image is to modify the run images configured in the builder. Unfortunately, this would change the builder's digest. 

Without this functionality builds will need to transfer a run image from dockerhub to the destination registry.

**Comment by matthewmcnew** [comment]
As discussed, @ArieShout @xscript.

**Comment by matthewmcnew** [comment]
Proposed addition to Builder spec:
```
stack:
   runImage:
       mirrors:
          - image: gcr.io/cloudfoundry/run:base-cnb
```

I would avoid configureable run image overrides until we complete: #79. 

We should also validate the mirrors have the same digest as the run image configured on the builder.

**Comment by joaopapereira** [comment]
The status of the builder should be:
```
status:
   stack:
      runImage: some-run-image@sha256:32165463513216351
      id: run.buildpacks.io
      mirrors:
         - image: gcr.io/some-run-image@sha256:32165463513216351
```

*Note:* If mirrors do not match the runImage digest, do not include them.
*Note2:* When creating a build only use the run images provided by on the builder status
