### ISSUE TITLE
Allowing of builder service account to run images as root.

### ISSUE THREAD

**Issue by GrahamDumpleton** [pivotal/kpack#195]
In a Kubernetes environment with multi tenancy enabled, where anything in namespaces are restricted to running pods in a set range of user IDs, or in any other setup where running as `root` is prohibited by default, it is necessary to create a `PodSecurityPolicy` and bind that to the service account to permit running as `root`.

It perhaps should be documented where defining:

```
apiVersion: v1
kind: ServiceAccount
metadata:
 name: tutorial-service-account
secrets:
 - name: tutorial-registry-credentials
```

that this would be required.
