### ISSUE TITLE
Add a stack resource

### ISSUE THREAD

**Issue by matthewmcnew** [pivotal/kpack#228]
Today, custom builders are configured with a `baseBuilderImage` which is essentially an empty [builder](https://buildpacks.io/docs/operator-guide/create-a-builder/). It would be convenient for users to be able to reference a stack such as those available on `pack suggest-stacks`. 

A stack resource would allow custom builders to be configured with a reference to a stack. This will allow updates to stack to fan out to all builders. This enables images to be rebased when used with custom builders.

**Comment by matthewmcnew** [comment]
With this change baseBuilderImage would no longer be a field on CustomBuilder.

```
apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: CustomBuilder
metadata:
  name: my-custom-builder
  namespace: default
spec:
  serviceAccount: default
  tag: sample/custom-builder
  stack: bionic
  store:
    image: cloudfoundry/cnb:bionic
  order:
  - group:
    - id: org.cloudfoundry.node-engine
    - id: org.cloudfoundry.yarn
  - group:
    - id: org.cloudfoundry.node-engine
    - id: org.cloudfoundry.npm  
```

```
apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: Stack
metadata:
  name: bionic
spec:
  baseImage:
    image: cf/cf
  runImage:
    image:  cf/cf
```
