### ISSUE TITLE
prepare:main.go:83: invalid credentials to build to spring-boot/image

### ISSUE THREAD

**Issue by cmoulliard** [pivotal/kpack#367]
## Issue

The initContainer - `prepare` created by kpack using this image `gcr.io/cf-build-service-public/kpack/build-init@sha256:b90a4d2c027ac6cf6b2904383211084d33d6faf9fed38a3d55a09b54e6f671bf` reports the following log message

```
prepare:main.go:83: invalid credentials to build to spring-boot/image
``` 

## How to reproduce

- Setu a k8s cluster 1.16
- Install `cf-for-k8s`
- Create a secret using your docker credentials
```
kubectl create secret generic my-docker-cred --from-file=.dockerconfigjson=/home/snowdrop/.docker/config.json --type=kubernetes.io/dockerconfigjson -n demo
```
- Deploy the following resources under by example the namespace `demo`
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-build-sa
secrets:
  - name: my-docker-cred
---
apiVersion: build.pivotal.io/v1alpha1
kind: Build
metadata:
  name: springboot-build
spec:
  tags:
    - spring-boot/image
  serviceAccount: my-build-sa
  builder:
    image: gcr.io/paketo-buildpacks/builder:base
    imagePullSecrets:
      - name: my-docker-cred
  source:
    git:
      url: https://github.com/cmoulliard/spring-music.git
      revision: master
  env:
    - name: "BP_BUILT_ARTIFACT"
      value: "build/libs/spring-music-*.jar"
```

## Questions

- Is the problem related to wrong docker hub credentials ?
- How can we get a more verbose logging message ?
