### ISSUE TITLE
Build-pod Init:Error When i create a image

### ISSUE THREAD

**Issue by hex-py** [pivotal/kpack#465]
### Problem Description:
  when i crete a image in namespace `default`,  status always false.
  - show images
```bash
     root@pc:~/$ kubectl get images
     NAME   LATESTIMAGE   READY
     demo                 False
```
     
  - show builds
```bash
    root@pc:~/$ kubectl get builds
     NAME                 IMAGE   SUCCEEDED
     demo-build-1-tml25           False
```
     
  - show pods
```bash
     root@pc:~/$ kubectl get pod
     NAME                           READY   STATUS       RESTARTS   AGE
     demo-build-1-tml25-build-pod   0/1     Init:Error   0          18m
```
    
  - describe pod
```yaml
Name:             demo-build-1-tml25-build-pod
    Namespace:   default
    Priority:           0
    Node:             hex-pc/192.168.10.240
    Start Time:     Wed, 05 Aug 2020 18:31:25 +0800
    Labels:           build.pivotal.io/build=demo-build-1-tml25
                          image.build.pivotal.io/buildNumber=1
                          image.build.pivotal.io/image=demo
                          image.build.pivotal.io/imageGeneration=1
    Annotations:  image.build.pivotal.io/reason: CONFIG
    Status:           Failed
    IP:                  172.17.0.12
    IPs:                <none>
    Controlled By:  Build/demo-build-1-tml25
    Init Containers:
      prepare:
        Container ID:  docker://b3e0a0fc44fb2f319704c0414caa4e4baddf1f2c89f44813819bb2b6693bf44d
        Image:            gcr.io/cf-build-service-public/kpack/build-init:1.0.0
        Image ID:       docker-pullable://gcr.io/cf-build-service-public/kpack/build-init@sha256:386452ea690ed497b092977209079c3f310e6fdf94523387e517df97f7f64cb3
        Port:          <none>
        Host Port:     <none>
    Args:
      --
      build-init
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 05 Aug 2020 18:31:25 +0800
      Finished:     Wed, 05 Aug 2020 18:31:29 +0800
    Ready:          False
    Restart Count:  0
    Environment:
      GIT_URL:            https://github.com/cloudfoundry-samples/cf-sample-app-nodejs.git
      GIT_REVISION:       2c7987ead3e5cc132bd3bd9fa3ff5ffa0cc7c508
      PLATFORM_ENV_VARS:  null
      IMAGE_TAG:          kpack/demo
      RUN_IMAGE:          index.docker.io/paketobuildpacks/run:base-cnb
    Mounts:
      /builder/home from home-dir (rw)
      /builderPullSecrets from builder-pull-secrets-dir (ro)
      /imagePullSecrets from image-pull-secrets-dir (ro)
      /platform from platform-dir (rw)
      /projectMetadata from layers-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xb6f6 (ro)
      /workspace from workspace-dir (rw)
```
  
### Resource:
- clusterBuilder
```yaml
  apiVersion: build.pivotal.io/v1alpha1
  kind: ClusterBuilder
  metadata:
    name: cluster-sample-builder
  spec:
    image: gcr.io/paketo-buildpacks/builder:base
    updatePolicy: polling
```

- image
``` yaml
apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: demo
spec:
  tag: kpack/demo
  #serviceAccount: controller
  builder: 
    name: default
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/cloudfoundry-samples/cf-sample-app-nodejs.git
      revision: master
```

### Environment:
- k8s: v1.15.6(minikube single node)
- kpack: 0.0.9
- docker: 19.03.4
