### ISSUE TITLE
custom builder image labels/metadata exceed max allowed size on KinD cluster w/ kubernetes v1.18

### ISSUE THREAD

**Issue by jamespollard8** [pivotal/kpack#473]
Hey kpack folks, Release Integration here

We're running into issues with cf-for-k8s `cf push`ing an app on our Kind clusters with kubernetes v1.18 (but not with k8s v1.16).

Here's what we're seeing when we describe our app staging pod that's attempting to use the custom builder image:
`Failed to pull image "gcr.io/cf-relint-greengrass/cf-workloads/cf-default-builder@sha256:40857aa32d2fe7167c914b63648c4ac0d6f6224e1d73ac6d6148d11c9e12f8c6": rpc error: code = InvalidArgument desc = failed to pull and unpack image "gcr.io/cf-relint-greengrass/cf-workloads/cf-default-builder@sha256:40857aa32d2fe7167c914b63648c4ac0d6f6224e1d73ac6d6148d11c9e12f8c6": failed to prepare extraction snapshot "extract-876130149-3tms sha256:f0dcba2cbeedc3702b4f390963e697b06360502302ec52e0d63bcfa7235220d1": info.Labels: label key and value greater than maximum size (4096 bytes), key: containerd: invalid argument`

and when we `docker inspect`, we can see that these 2 labels are particularly long:
```
"Labels": {
                "io.buildpacks.builder.metadata":
...
                "io.buildpacks.buildpack.layers" <-- this one is gigantic
...
}

Here's our relevant configuration, which we don't think is particularly crazy and had been working for us until recently: https://github.com/cloudfoundry/cf-for-k8s/blob/d8245bd07135c8d21d771e09571b7f93247b64b8/config/kpack/default-buildpacks.yml

We'd love to hear your feedback on that file and if you have any suggestions for fixes for us here; this is currently a major blocker for us.

**Comment by matthewmcnew** [comment]
cc @jromero

**Comment by jromero** [comment]
Looking at the error message text I was able to find what I believe is the [source](https://github.com/jessvalarezo/containerd/blob/18c4322bb3ddcb8f8b4eea2f3c027a06194041b4/labels/validate.go) producing it and the [issue](https://github.com/containerd/containerd/issues/1513) referring to it.

**Comment by davewalter** [comment]
We tried deploying on Kind with K8s v1.16.9 and the same version of cf-for-k8s. When we pushed our test node app to the platform, we were initially surprised to see that the digest for the cf-default-builder image was identical to the one created with K8s v1.18.6, but on reflection, this seems to make sense, given that the builder/stack and store definitions are all identical.

We next tried removing all of the buildpacks, with the exception of the Node JS buildpack that is required for our sample app. For reference, here is the store/stack/builder definitions we deployed:
```
#@ load("@ytt:data", "data")

---
apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: Store
metadata:
  name: cf-buildpack-store
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/nodejs@sha256:7110ff41a35ec4d8a0fbb63e7b292c2edc7ef0e072e542cd0a58e5d179ce2605

---
apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: Stack
metadata:
  name: cflinuxfs3-stack
spec:
  id: "org.cloudfoundry.stacks.cflinuxfs3"
  buildImage:
    image: "gcr.io/paketo-buildpacks/build@sha256:84f7b60192e69036cb363b2fc7d9834cff69dcbcf7aaf8c058d986fdee6941c3"
  runImage:
    image: "gcr.io/paketo-buildpacks/run@sha256:84f7b60192e69036cb363b2fc7d9834cff69dcbcf7aaf8c058d986fdee6941c3"

---
apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: CustomBuilder
metadata:
  name: cf-default-builder
  namespace: #@ data.values.staging_namespace
spec:
  tag: #@ "{}/cf-default-builder".format(data.values.app_registry.repository_prefix)
  serviceAccount: cc-kpack-registry-service-account
  stack: cflinuxfs3-stack
  store: cf-buildpack-store
  order:
  - group:
    - id: paketo-buildpacks/nodejs
```

This did result in a new builder image, which had much smaller annotations:
```
[
    {
        ...
        "Config": {
            ...
            "Labels": {
                "io.buildpacks.builder.metadata": "{\"description\":\"Custom Builder built with kpack\",\"stack\":{\"runImage\":{\"image\":\"gcr.io/paketo-buildpacks/run@sha256:84f7b60192e69036cb363b2fc7d9834cff69dcbcf7aaf8c058d986fdee6941c3\",\"mirrors\":null}},\"lifecycle\":{\"version\":\"0.8.1\",\"api\":{\"buildpack\":\"0.2\",\"platform\":\"0.3\"}},\"createdBy\":{\"name\":\"kpack CustomBuilder\",\"version\":\"v0.0.10 (git sha: 68925eaca94becfeef006c413ebac4fde559e66c)\"},\"buildpacks\":[{\"id\":\"paketo-buildpacks/node-engine\",\"version\":\"0.0.260\",\"homepage\":\"https://github.com/paketo-buildpacks/node-engine\"},{\"id\":\"paketo-buildpacks/yarn-install\",\"version\":\"0.1.86\",\"homepage\":\"https://github.com/paketo-buildpacks/yarn-install\"},{\"id\":\"paketo-buildpacks/npm\",\"version\":\"0.1.79\",\"homepage\":\"https://github.com/paketo-buildpacks/npm\"},{\"id\":\"paketo-buildpacks/nodejs\",\"version\":\"0.0.5\",\"homepage\":\"https://github.com/paketo-buildpacks/nodejs\"}]}",
                "io.buildpacks.buildpack.layers": "{\"paketo-buildpacks/node-engine\":{\"0.0.260\":{\"api\":\"0.2\",\"layerDiffID\":\"sha256:7d57d604f4efbf533639810fc3d590b2c334382097f4cdd4c3d5bcfaf8b1bd15\",\"stacks\":[{\"id\":\"io.buildpacks.stacks.bionic\"},{\"id\":\"org.cloudfoundry.stacks.cflinuxfs3\"}],\"homepage\":\"https://github.com/paketo-buildpacks/node-engine\"}},\"paketo-buildpacks/nodejs\":{\"0.0.5\":{\"api\":\"0.2\",\"layerDiffID\":\"sha256:71dd90c6ed436af5fd5027789c76ef7bc19d71ea2b46ec602dbdbe0c6e7ee9af\",\"order\":[{\"group\":[{\"id\":\"paketo-buildpacks/node-engine\",\"version\":\"0.0.260\"},{\"id\":\"paketo-buildpacks/yarn-install\",\"version\":\"0.1.86\"}]},{\"group\":[{\"id\":\"paketo-buildpacks/node-engine\",\"version\":\"0.0.260\"},{\"id\":\"paketo-buildpacks/npm\",\"version\":\"0.1.79\"}]}],\"homepage\":\"https://github.com/paketo-buildpacks/nodejs\"}},\"paketo-buildpacks/npm\":{\"0.1.79\":{\"api\":\"0.2\",\"layerDiffID\":\"sha256:687909d9abefc647892cbe213a425cf37097f5cd96eb79987f5fab4eb8b6af18\",\"stacks\":[{\"id\":\"org.cloudfoundry.stacks.cflinuxfs3\"},{\"id\":\"io.buildpacks.stacks.bionic\"}],\"homepage\":\"https://github.com/paketo-buildpacks/npm\"}},\"paketo-buildpacks/yarn-install\":{\"0.1.86\":{\"api\":\"0.2\",\"layerDiffID\":\"sha256:25eefd03f95bf374fa44cadd0fc7a9c7ef943ba1a7faa0fc90379786e0c07b21\",\"stacks\":[{\"id\":\"org.cloudfoundry.stacks.cflinuxfs3\"},{\"id\":\"io.buildpacks.stacks.bionic\"}],\"homepage\":\"https://github.com/paketo-buildpacks/yarn-install\"}}}",
                "io.buildpacks.buildpack.order": "[{\"group\":[{\"id\":\"paketo-buildpacks/nodejs\",\"version\":\"0.0.5\"}]}]",
                "io.buildpacks.stack.id": "org.cloudfoundry.stacks.cflinuxfs3"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 1085920101,
        "VirtualSize": 1085920101,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/ed68aeaecb6b741619bb19701aaa44de0ffec69b0c9ae506925df5885fcf89db/diff:/var/lib/docker/overlay2/c0d8b46fab8cc1bd50fafb8c488bff78dfded88e7fdac52fbf3d03a6f61dc5bd/diff:/var/lib/docker/overlay2/c055453ec8328a06aea7e48fa15532749c111b36b9de976263bf51ca351451d2/diff:/var/lib/docker/overlay2/edd6efe0267833bbce1f84157c7ec0cac1cdac63e51a6d825793c84d6bd3d328/diff:/var/lib/docker/overlay2/14b725c618f9984cdbd685ca3b475ee39cad8598a5dd246411bb1db5d97ddad3/diff:/var/lib/docker/overlay2/d1999b90d1a3b57d9c63e0167e1602ed090ec4e05d9e3642fbc8961a67be3a35/diff:/var/lib/docker/overlay2/4616983ec5476539812eab442d439f404364f9c8e70c7278f9958542159ea939/diff:/var/lib/docker/overlay2/1cc6f315cab22e27897441b185a7d637764766565c7f719c702a9c780b3cc18d/diff",
                "MergedDir": "/var/lib/docker/overlay2/36d812a5c093893dfc5308adb9433af8d977568e342c5f4b509b7a6a77008f39/merged",
                "UpperDir": "/var/lib/docker/overlay2/36d812a5c093893dfc5308adb9433af8d977568e342c5f4b509b7a6a77008f39/diff",
                "WorkDir": "/var/lib/docker/overlay2/36d812a5c093893dfc5308adb9433af8d977568e342c5f4b509b7a6a77008f39/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:f0dcba2cbeedc3702b4f390963e697b06360502302ec52e0d63bcfa7235220d1",
                "sha256:7755b972f0b4f49de73ef5114fb3ba9c69d80f217e80da99f56f0d0a5dcb3d70",
                "sha256:c33cb7212a62bb159674eae50b7ace60bb7c73c70ea6f8597c72fff10189d78f",
                "sha256:7d57d604f4efbf533639810fc3d590b2c334382097f4cdd4c3d5bcfaf8b1bd15",
                "sha256:25eefd03f95bf374fa44cadd0fc7a9c7ef943ba1a7faa0fc90379786e0c07b21",
                "sha256:687909d9abefc647892cbe213a425cf37097f5cd96eb79987f5fab4eb8b6af18",
                "sha256:71dd90c6ed436af5fd5027789c76ef7bc19d71ea2b46ec602dbdbe0c6e7ee9af",
                "sha256:3ae93fd59e3e53f9d0cbea42625e12139a7fb8a59915dc23b0219a01a44e018f",
                "sha256:a7ce12a420636d1b1726e67e67055a3ead31453018be5c32019420cb9e3786ba"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```
We're not sure how this information helps, given that we are still unsure as to exactly which part of the image containerd is complaining about.
