### ISSUE TITLE
Private DTR registry fails to build

### ISSUE THREAD

**Issue by vijayb47** [pivotal/kpack#482]
I am trying to use a private registry, Docker Trusted Registry, to save the images. 

Secret yaml looks like:

```
apiVersion: v1
kind: Secret
metadata:
  name: dtr-credentials
  annotations:
    build.pivotal.io/docker: https://registry.privatehosting.com/v1/
type: kubernetes.io/basic-auth
stringData:
  username: johndoe
  password: supersecret
```

SA yaml:

```
apiVersion: v1
kind: ServiceAccount
metadata:
 name: dtr-service-account
secrets:
 - name: dtr-credentials
```

Image file looks like:

```
apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: petstore-image-dtr2
spec:
  tag: registry.privatehosting.com/platform-srvs/petstore
  serviceAccount: dtr-service-account
  cacheSize: "1.5Gi"
  builder:
    name: base-cluster-builder
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/xxxx/spring-petclinic
      revision: master
```

But, I noticed that the image and build status is "False" right away (instead of unknown). Only useful info I see is on build describe:

```
Status:
  Conditions:
    Last Transition Time:  2020-08-19T20:36:13Z
    Message:               No API token found for service account "dtr-service-account", retry after the token is automatically created and added to the service account
    Status:                False
    Type:                  Succeeded
  Observed Generation:     1
  Stack:
```

The secret and sa that I created for hub.docker.com worked as expected but above private registry/repo so wondering whether kpack support private registries? Or am I missing not supplying secrets properly?

**Comment by matthewmcnew** [comment]
Hi @vijayb47, 

The `build.pivotal.io/docker` annotation on your secret should be `registry.privatehosting.com`. 

However, the `No API token found for service account` error appears to be an issue with your underlying kubernetes. What version of kubernetes are you using and where is it running?

**Comment by vijayb47** [comment]
Hi @matthewmcnew,
thank you the annotation note. Further debugging revealed that the Secrets in the GKE private cluster. It is running on 1.15.

Now I am trying kpack 0.1x. I am now trying in AKS cluster on 1.16.13. Trying to update the manifests (Store object etc) and apply them again. 

It's a totally different issue but getting error while trying to set store.yml:
```
apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: default
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/java
  - image: gcr.io/paketo-buildpacks/nodejs
```
k apply -f store.yml
error: unable to recognize "store.yml": no matches for kind "ClusterStore" in version "kpack.io/v1alpha1"

Any Custom object needs to be created before we apply store? Let me know if you want me to open a new issue for this.

thank you
