### ISSUE TITLE
Support k8s Service Bindings

### ISSUE THREAD

**Issue by matthewmcnew** [pivotal/kpack#536]
With [CNB Service bindings deprecated ](https://github.com/buildpacks/rfcs/pull/105) the new [k8s service bindings spec](https://k8s-service-bindings.github.io/spec/) should be supported. 

The CF Capi team needs this functionality to add service bindings to cf pushed apps during build. 

The outstanding question is how to model this in the image spec and in what timeframe we will deprecate the old service bindings.

**Comment by djoyahoy** [comment]
The new spec should be low effort to support. We would need to do the following:
1. Modify the image config to take a list of objectRefs instead of secrets + configmaps for service bindings.
2. a. During build reconciliation, find the service objects from the objectRefs list, and use their binding names to mount secret volumes into the build pod.
2. b. Use the `SERVICE_BINDING_ROOT` env var from the image config as the mount path root if provided. Otherwise, use `/bindings`.
2. c. Everything else remains the same.

To add support for this feature, I would recommend bumping the image config version from `v1alpha1` to `v1alpha2` or `v1beta1` and dropping the support for CNB style bindings in the latest image config version.

Alternatively, we simply add a new field to the image config and use the same version, while maintaining support for both binding specs. This may cause some confusion for our users.

**Comment by tylerphelan** [comment]
Migration path Image v1alpha1 -> v1alpha2

Old bindings config:

```
kind: Image
spec:
  build:
    bindings:
    - name: settings
       secretRef:
         name: settings-xml
       metadataRef:
         name: settings-binding-metadata
---
apiVersion: v1
kind: Secret
metadata:
  name: settings-xml
type: Opaque
stringData:
  settings.xml: <settings>...</settings>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: settings-binding-metadata
data:
  kind: maven
  provider: sample
```

Directory structure of old bindings:

```
<platform>
└── bindings
    └── settings
        ├── metadata
        │   ├── kind
        │   └── provider
        └── secret
            └── setting.xml
```

The same config should create the following directory structure for new bindings:

```
$SERVICE_BINDING_ROOT
├── settings
│   ├── type
│   ├── provider
│   ├── setting.xml
```

Doesn't seem too complex

**Comment by matthewmcnew** [comment]
It seems like the complication is how to handle to represent both the old/new service bindings in both  v1alpha1/v1alpha2 api versions. 

Also of note, this information needs to be represented on the build as well.

**Comment by matthewmcnew** [comment]
```
    bindings:
    - name: settings
      service:
        name: settings-xml
        kind: Secret
```

What is the benefit of giving the binding its own name?
