### ISSUE TITLE
validating webhook preventing deletion of clusterbuilder

### ISSUE THREAD

**Issue by cirocosta** [pivotal/kpack#552]
Hi folks!

I created a `ClusterBuilder` out of what seems to be an old syntax

```
apiVersion: kpack.io/v1alpha1
kind: ClusterBuilder
metadata:
  name: golang-kpack-builder
spec:
  serviceAccount: kpack-builder
  tag: <some_tag>
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
    - group:
        - id: paketo-buildpacks/go
```

but then when deleting it, I simply couldn't:

```
Error from server (BadRequest): error when deleting "./config/kpack/golang.yaml": admission webhook "validation.webhook.kpack.io" denied the request: decoding request failed: cannot decode incoming old object: json: unknown field "serviceAccount"
```

to resolve, I temporarily got rid of the `validatingwebhookconfiguration` which did the job.

using the new syntax works great, so nothing is really blocking me, but other people might land into this same problem.

version: 0.1.3 (https://github.com/pivotal/kpack/releases/download/v0.1.3/release-0.1.3.yaml) 

thanks!
