### ISSUE TITLE
http: server gave HTTP response to HTTPS client'

### ISSUE THREAD

**Issue by cmoulliard** [pivotal/kpack#634]
## Issue

When the following builder is deployed on k8s (using cf-for-k8s) using the following local registry
```
app_registry:
  hostname: https://kube-registry.kube-system.svc:5000
  repository_prefix: kube-registry.kube-system.svc:5000
  username: "cmoulliard" 
  password: "dabou"
```
then we got this error
```
message: 'Get "https://kube-registry.kube-system.svc:5000/v2/": http: server gave HTTP response to HTTPS client'
```

Is there a way to configure how kpack to avoid such an error ?

### Builder resource
```
apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  labels:
    kapp.k14s.io/app: "1614848592205033102"
    kapp.k14s.io/association: v1.8f280237cae4d1d3dc679f61db1f417e
  name: cf-default-builder
  namespace: cf-workloads-staging
spec:
  order:
  - group:
    - id: paketo-buildpacks/ruby
  - group:
    - id: paketo-buildpacks/dotnet-core
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/nodejs
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/go
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-community/python
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/php
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/nginx
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/httpd
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/procfile
  serviceAccount: cc-kpack-registry-service-account
  stack:
    kind: ClusterStack
    name: bionic-stack
  store:
    kind: ClusterStore
    name: cf-buildpack-store
  tag: kube-registry.kube-system.svc:5000/cf-default-builder
```
### Kpack controller resource
```
kind: Pod
apiVersion: v1
metadata:
  name: kpack-controller-7dcd4d99bb-hpw68
  namespace: kpack
  labels:
    app: kpack-controller
    istio.io/rev: default
    kapp.k14s.io/app: '1614848592205033102'
    kapp.k14s.io/association: v1.56b896e1b066dc77f33b02834ae3dca9
    pod-template-hash: 7dcd4d99bb
    security.istio.io/tlsMode: istio
    service.istio.io/canonical-name: kpack-controller
    service.istio.io/canonical-revision: 0.2.0-rc.1
    version: 0.2.0-rc.1
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: kpack-controller-7dcd4d99bb
      uid: bd634309-90f3-49fb-b6ef-2022d538c229
      controller: true
      blockOwnerDeletion: true
spec:
  volumes:
    - name: controller-token-vrs92
      secret:
        secretName: controller-token-vrs92
        defaultMode: 420
  containers:
    - name: controller
      image: >-
        gcr.io/cf-build-service-public/kpack/controller@sha256:101143de3d1abe2d2f738ce96b5991cd085ecc6f0e8dc761b940dd1cd346b864
      env:
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: kpack.io
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: BUILD_INIT_IMAGE
          valueFrom:
            configMapKeyRef:
              name: build-init-image
              key: image
        - name: BUILD_INIT_WINDOWS_IMAGE
          valueFrom:
            configMapKeyRef:
              name: build-init-windows-image
              key: image
        - name: REBASE_IMAGE
          valueFrom:
            configMapKeyRef:
              name: rebase-image
              key: image
        - name: COMPLETION_IMAGE
          valueFrom:
            configMapKeyRef:
              name: completion-image
              key: image
        - name: COMPLETION_WINDOWS_IMAGE
          valueFrom:
            configMapKeyRef:
              name: completion-windows-image
              key: image
        - name: LIFECYCLE_IMAGE
          valueFrom:
            configMapKeyRef:
              name: lifecycle-image
              key: image
      resources: {}
      volumeMounts:
        - name: controller-token-vrs92
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  nodeSelector:
    kubernetes.io/os: linux
  serviceAccountName: controller
  serviceAccount: controller
  nodeName: h01-118
  securityContext:
    fsGroup: 1337
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
```

**Comment by cmoulliard** [comment]
How we can debug or try to understand the error reported within the log the pod of the kpack controller and more precisely by knative controller `knative.dev/pkg/controller/controller.go:403` ?
```
{"level":"info","ts":"2021-03-08T18:17:51.059Z","logger":"controller.ClusterStores","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 1.36745019s","commit":"c2ceeca","knative.dev/traceid":"2d250b7b-f154-4166-af75-59d5e7e69678","knative.dev/key":"cf-buildpack-store"}
{"level":"info","ts":"2021-03-08T18:17:51.827Z","logger":"controller.Stacks","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 2.136346509s","commit":"c2ceeca","knative.dev/traceid":"1b18bb19-52f9-468e-b580-f3d9466e8faf","knative.dev/key":"bionic-stack"}
{"level":"error","ts":"2021-03-08T18:17:52.098Z","logger":"controller.Builders","caller":"controller/controller.go:480","msg":"Reconcile error","commit":"c2ceeca","error":"Get \"https://kube-registry.infra:5000/v2/\": http: server gave HTTP response to HTTPS client","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\t/workspace/vendor/knative.dev/pkg/controller/controller.go:480\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\t/workspace/vendor/knative.dev/pkg/controller/controller.go:466\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\t/workspace/vendor/knative.dev/pkg/controller/controller.go:403"}
{"level":"info","ts":"2021-03-08T18:17:52.098Z","logger":"controller.Builders","caller":"controller/controller.go:467","msg":"Reconcile failed. Time taken: 2.406866966s","commit":"c2ceeca","knative.dev/traceid":"fe1f219d-ccd3-4023-896e-c80c9fc77c13","knative.dev/key":"cf-workloads-staging/cf-default-builder"}
```

**Comment by matthewmcnew** [comment]
@cmoulliard It looks like kpack is attempting to use https with `kube-registry.kube-system.svc:5000` and the registry only supports http. 

kpack does not currently explicitly provide support for accessing an insecure registry over `http`. However, kpack utilizes http://github.com/google/go-containerregistry which will fall back to `http` in a few different [cases](https://github.com/google/go-containerregistry/blob/e1c5762cb945605669ed5fcb3124e3f839e5cc79/pkg/name/registry.go#L84). 

[Conveniently](https://github.com/google/go-containerregistry/blob/e1c5762cb945605669ed5fcb3124e3f839e5cc79/pkg/name/registry.go#L31), accessing registries with the kubernetes dns record `*.cluster.local` are available via `http` such as `kube-registry.kube-system.cluster.local`.

**Comment by cmoulliard** [comment]
> Could you try configuring the cf registry as `kube-registry.kube-system.svc.cluster.local`. (Note: this will fall back to http inside kpack)

I did a test and now I get such an error
```
kapp: Error: waiting on reconcile builder/cf-default-builder (kpack.io/v1alpha1) namespace: cf-workloads-staging:
  Finished unsuccessfully (Encountered failure condition Ready == False:  (message: GET http://kube-registry.infra.svc.cluster.local:5000/v2/: unsupported status code 503; body: upstream connect error or disconnect/reset before headers. reset reason: connection termination))
```

The log of the Docker registry reports 
```
2021/03/09 07:48:49 http: TLS handshake error from 10.244.0.1:46378: tls: first record does not look like a TLS handshake
2021/03/09 07:48:49 http: TLS handshake error from 10.244.0.1:46392: tls: first record does not look like a TLS handshake
```
FYI: Here is the config that I'm using to access the provate registry
```
app_registry:
  hostname: http://kube-registry.infra.svc.cluster.local:5000
  repository_prefix: kube-registry.infra.svc.cluster.local:5000
  username: "admin"
  password: "xxxxxx"
```

**Comment by cmoulliard** [comment]
The trick to use the `HTTPS` address of the private docker registry and self signed certificate is to update the Kpack controller definition and to mount the secret containing the certificate and key as I did (see hereafter).

**IMPORTANT**: I dont think that we can do that when kpack is deployed using `cf-for-k8s`

```
kc delete deployment/kpack-controller -n kpack
cat <<EOF | kubectl apply -n kpack -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpack-controller
  namespace: kpack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpack-controller
  template:
    metadata:
      labels:
        app: kpack-controller
        version: 0.2.2-rc.1
    spec:
      serviceAccountName: controller
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
        - name: custom-certs
          secret:
            secretName: cert-key
      containers:
        - name: controller
          image: gcr.io/cf-build-service-public/kpack/controller@sha256:ec256da7e29eeecdd0821f499e754080672db8f0bc521b2fa1f13f6a75a04835
          volumeMounts:
            - name: custom-certs
              mountPath: /certs
          env:
            - name: SSL_CERT_DIR
              value: /certs
            - name: CONFIG_LOGGING_NAME
              value: config-logging
            - name: CONFIG_OBSERVABILITY_NAME
              value: config-observability
            - name: METRICS_DOMAIN
              value: kpack.io
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: BUILD_INIT_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: build-init-image
                  key: image
            - name: BUILD_INIT_WINDOWS_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: build-init-windows-image
                  key: image
            - name: REBASE_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: rebase-image
                  key: image
            - name: COMPLETION_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: completion-image
                  key: image
            - name: COMPLETION_WINDOWS_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: completion-windows-image
                  key: image
            - name: LIFECYCLE_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: lifecycle-image
                  key: image
          resources:
            requests:
              cpu: 20m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 400Mi
EOF
```

**Comment by tylerphelan** [comment]
@cmoulliard you could try using this to set up the cert: https://github.com/vmware-tanzu/cert-injection-webhook

**Comment by matthewmcnew** [comment]
@cmoulliard The cert injection webhook has different goals from cert-manager.

The cert injection webhook is designed to inject certs into pods so that the resulting pods trust the cert (similar to what you did [here](https://github.com/pivotal/kpack/issues/634#issuecomment-793739917))

**Comment by matthewmcnew** [comment]
Yes, the resulting build pods will also need the cert configured so that they know to trust the registry. To accomplish that you can either:
1. Add the cert to the clusterstack build image
2. Utilize https://github.com/vmware-tanzu/cert-injection-webhook as Tyler mentioned earlier to "inject" the cert into the build pods.

**Comment by cmoulliard** [comment]
> 1. Add the cert to the clusterstack build image

 To this k8s resource then ? Manually ?
```
kc describe clusterstack
Name:         base
Namespace:
Labels:       <none>
Annotations:  API Version:  kpack.io/v1alpha1
Kind:         ClusterStack
Metadata:
  Creation Timestamp:  2021-03-10T08:01:30Z
  Generation:          1
Spec:
  Build Image:
    Image:  paketobuildpacks/build:base-cnb
  Id:       io.buildpacks.stacks.bionic
  Run Image:
    Image:  paketobuildpacks/run:base-cnb
```

**Comment by cmoulliard** [comment]
> 2\. as Tyler mentioned earlier to "inject" the cert into the build pods.

I did a test yesterday and was not able to configure it with labels, ...

**Comment by cmoulliard** [comment]
> that has the necessary cert in it

Any idea where the certificate/key files should be `COPY` by docker during the build of the image ?

**Comment by matthewmcnew** [comment]
You would want to do something like this: 

```
USER root
ADD your_ca_root.crt /usr/local/share/ca-certificates/foo.crt
RUN chmod 644 /usr/local/share/ca-certificates/foo.crt && update-ca-certificates
USER CNB
```

However, I just realized that would still not provide the cert to the first step of the build (prepare) where you are currently seeing a failure. You would also need to build a new image with the new cert of the kpack build-init as well. So, I would recommend you use the cert injection webhook as the easiest path forward.

**Comment by matthewmcnew** [comment]
Correct.

**Comment by cmoulliard** [comment]
No luck. Here is the pod of the image created where annotation `kpack.io/build: certificate` has been added
```
kind: Pod
metadata:
  annotations:
    image.kpack.io/buildChanges: '[{"reason":"CONFIG","old":{"resources":{},"source":{}},"new":{"resources":{},"source":{"git":{"url":"https://github.com/sp
ring-projects/spring-petclinic","revision":"82cb521d636b282340378d80a6307a08e3d4a4c4"}}}}]'
    image.kpack.io/reason: CONFIG
    kpack.io/build: certificate
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kpack.io/v1alpha1","kind":"Image","metadata":{"annotations":{"kpack.io/build":"certificate"},"name":"tutorial-image","namespace":"demo"
},"spec":{"builder":{"kind":"Builder","name":"my-builder"},"serviceAccount":"tutorial-service-account","source":{"git":{"revision":"82cb521d636b282340378d80
a6307a08e3d4a4c4","url":"https://github.com/spring-projects/spring-petclinic"}},"tag":"kube-registry.infra.svc:5000/tutorial"}}
  creationTimestamp: "2021-03-10T19:03:02Z"
  labels:
    image.kpack.io/buildNumber: "1"
    image.kpack.io/image: tutorial-image
    image.kpack.io/imageGeneration: "1"
    kpack.io/build: tutorial-image-build-1-zcbvv
...
```
here is the ytt command used `ytt -f ./deployments/k8s -v pod_webhook_image=cmoulliard/my-cert-webhook -v setup_ca_certs_image=cmoulliard/my-setup-ca-certs --data-value-file ca_cert_data=/etc/pki/tls/certs/server.crt --data-value-yaml annotations="[kpack.io/build=certificate]" > manifest.yaml`

and manifest generated
```
...
containers:
      - name: server
        image: cmoulliard/my-cert-webhook
        imagePullPolicy: Always
        args:
        - -annotation=kpack.io/build=certificate
```
but still got
```
===> PREPARE
Build reason(s): CONFIG
CONFIG:
	resources: {}
	- source: {}
	+ source:
	+   git:
	+     revision: 82cb521d636b282340378d80a6307a08e3d4a4c4
	+     url: https://github.com/spring-projects/spring-petclinic
Loading secret for "https://kube-registry.infra.svc:5000/" from secret "tutorial-registry-credentials" at location "/var/build-secrets/tutorial-registry-credentials"
Error verifying write access to "kube-registry.infra.svc:5000/tutorial": Get "https://kube-registry.infra.svc:5000/v2/": x509: certificate signed by unknown authority
```
