### ISSUE TITLE
Create ClusterBuilder resource

### ISSUE THREAD

**Issue by matthewmcnew** [pivotal/kpack#72]
A ClusterBuilder would allow a single builder resource to be shared across the entire cluster and used in multiple namespaces. 

As an operator of the Build Service one or more ClusterBuilders could be made available in a namespace where users do not have permission to create builders. This would allow a builder to be configured for many 'tenants'. 

```
apiVersion: build.pivotal.io/v1alpha1
kind: ClusterBuilder
metadata:
  name: multi-team-builder
spec:
  image: cloudfoundry/cnb:bionic
```

A Image resource could be configured to to use that builder:
```
apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: sample-image
spec:
  tag: gcr.io/project-name/app
  builderRef: 
   name: multi-team-builder
   kind: ClusterBuilder
....
``` 

The builderRef kind should default to builder.
