### ISSUE TITLE
Allow configuration of Run Image in Builder CRD

### ISSUE THREAD

**Issue by joaopapereira** [pivotal/kpack#79]
Allow the user to specify a Run Image that would override the one present in the builder.

The interface to create a builder could be something like the following
```
apiVersion: build.pivotal.io/v1alpha1
kind: Builder
metadata:
  name: sample-builder
spec:
  image: cloudfoundry/cnb:bionic
  updatePolicy: polling
  stack: # Optional field
    runImage:
      image: cloudfoundry/run:base-cnb # Mandatory
      mirrors:
        - image: gcr.io/cloudfoundry/run:base-cnb
```
This `runImage` field should be optional and if no value is provided the run image that was "packaged" on the Builder Image should be used.

Also the status of the Builder should provide a resolved runImage(repo:tag@sha256:dasd).

Status should look like:
```
apiVersion: build.pivotal.io/v1alpha1
kind: Builder
...
status:
  builderMetadata:
    - key: org.cloudfoundry.node-engine
      version: 0.0.26
  conditions:
    - lastTransitionTime: null
      status: "True"
      type: Ready
  latestImage: index.docker.io/cloudfoundry/cnb@sha256:1640c42e4bce59c400f9c648e
  stack:
    runImage:
      image: index.docker.io/cloudfoundry/run@sha256:1123543ad45cf
```

**Note**: The `stack` can be optional but when provided at least the `runImage.image` fields need to be provided
