### ISSUE TITLE
Question: Release version tagged is 0.3.1 but version of the release.yaml file  is 0.3.1-rc.3

### ISSUE THREAD

**Issue by cmoulliard** [pivotal/kpack#831]
## Question

Why is the release version tagged under github `0.3.1` but version declared within of the kubernetes release.yaml file is `0.3.1-rc.3` ? Is it a mistake ? Are the images sha of the release.yaml correct ?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpack-controller
  namespace: kpack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpack-controller
  template:
    metadata:
      labels:
        app: kpack-controller
        version: 0.3.1-rc.3
    spec:
      serviceAccountName: controller
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: controller
        image: gcr.io/cf-build-service-public/kpack/controller@sha256:4b3c825d6fb656f137706738058aab59051d753312e75404fc5cdaf49c352867
```

**Comment by matthewmcnew** [comment]
All published released yamls includes the internal release release candidate.

**Comment by cmoulliard** [comment]
This is a bad practice to include within a released file a `-rc.x` suffix while the resource is part of a tagged release

Example of such suffix added for this release: https://github.com/pivotal/kpack/releases/download/v0.6.0/release-0.6.0.yaml
```
      labels:
        app: kpack-webhook
        role: webhook
        version: 0.6.0-rc.7
```
