### ISSUE TITLE
Tutorial not working

### ISSUE THREAD

**Issue by RadiatorSpring** [pivotal/kpack#859]
There seems to be bug when trying to set `serviceAccountName` for `Builder`

```
apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: test-builder
  namespace: default
spec:
  serviceAccountName: kneo-service-account
  tag: <repo>/builder:base
  stack:
    name: base
    kind: ClusterStack
  store:
    name: kneo-cluster-store
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/apache-tomcat
    - id: paketo-buildpacks/sap-machine
```
I get this error 
`    Message:                  GET https://kneo-sofia.docker.repositories.cloud.sap:443/artifactory/api/docker/kneo-sofia/v2/token?scope=repository%3Abuilder%3Apush%2Cpull&scope=repository%3Akneo-buildpack%3Apull&service=kneo-sofia.docker.repositories.cloud.sap%3A443: : Authentication is required`

But when I change `serviceAccountName` to `serviceAccount` it works.
Is this bug in the documentation or am I doig something wrong ?
