### ISSUE TITLE
Builder unable to authenticate to private registry when pulling lifecycle

### ISSUE THREAD

**Issue by dazzla76** [pivotal/kpack#882]
I am currently unable to get a Builder or ClusterBuilder object into a ready state.  It is erroring with a message that it cannot fetch the lifecycle image.

`failed to fetch lifecycle image: GET https://registry.company.com/jwt/auth?scope=repository%3Aplatform%2Fcontainer-images%2Fkpack%2Flifecycle%3Apull&service=container_registry: DENIED: access forbidden`

- I've checked that the kpack deployment specifies the internal copy of the lifecycle image
- I've verified that the credentials i am using can pull the image using podman/docker
- I've specified the ServiceAccountRef the same as i have done for the ClusterStore and stack which both have a status of ready

my builder.yaml looks like this:

```
apiVersion: kpack.io/v1alpha1
kind: ClusterBuilder
metadata:
  name: my-builder
  namespace: kpack
spec:
  serviceAccountRef:
    namespace: kpack
    name: registry-service-account
  tag: registry.company.nomura.com:5050/paasplatform/container-images/nomura-ubi8-builder-new:latest
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
  - group:
    - id: gitlab-prem.nomura.com:5050/platform/container-images/nomura-ubi8-builder:latest
```

the controller logs are showing the following, although it appears to be a more verbose version of the error above

`{"severity":"ERROR","timestamp":"2021-11-12T15:19:03.747861605Z","logger":"controller","caller":"controller/controller.go:564","message":"Reconcile error","commit":"ab7c188","duration":"39.116443ms","error":"failed to fetch lifecycle image: GET https://registry.company.com/jwt/auth?scope=repository%3Aplatform%2Fcontainer-images%2Fkpack%2Flifecycle%3Apull&service=container_registry: DENIED: access forbidden","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20210902173607-844a6bc45596/controller/controller.go:564\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20210902173607-844a6bc45596/controller/controller.go:541\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20210902173607-844a6bc45596/controller/controller.go:477"}`

**Comment by dazzla76** [comment]
Actually, I've just realized the error doesn't mention the port (5050) anywhere.  is it possible the controller is removing that from the url for some reason?

**Comment by tylerphelan** [comment]
@dazzla76 as of kpack v0.4.0 you can configure a serviceAccount in the `lifecycle-image` ConfigMap for private registry access:
```
apiVersion: v1
data:
  image: <lifecycle-image-ref>
  serviceAccountRef.name: <service-account-name>
  serviceAccountRef.namespace: <service-account-namespace>
kind: ConfigMap
metadata:
  name: lifecycle-image
  namespace: kpack
```
