### ISSUE TITLE
Build fails with "message: resource name may not be empty" status when the ServiceAccount has an empty secret ref in its imagePullSecrets

### ISSUE THREAD

**Issue by tcdowney** [pivotal/kpack#956]
Hey all 👋 

We had a tricky to debug issue with our kpack `Builds` failing with a status condition indicating that `"message: resource name may not be empty"`. It was difficult to discover why this error was occurring and tailing logs for the kpack controller didn't reveal any additional information. After some trial and error I was able to narrow it down to the fact that our `ServiceAccount` had an empty `localObjectReference` element in its `secrets`/`imagePullSecrets` arrays. After I fixed that to point at an existing secret the new kpack `Builds` for our `Image` succeeded. I think some additional logging or an improved error messaging here could be helpful.

I'm not very familiar with the code, but I'm wondering if the error is raised somewhere around here:
https://github.com/pivotal/kpack/blob/eb84c15f51b3d95fffe982679028471881d4f35c/pkg/buildpod/generator.go#L178

### Example Resources
Attached are a version of the kpack `Build` I was using as well as an example of the bad `ServiceAccount` and a working one.

Kpack Build Example:
_Modified slightly to remove repo addresses / some not relevant data._

```yaml
apiVersion: kpack.io/v1alpha2
kind: Build
metadata:
  ...
  name: 1fe1df52-f6a8-4065-b335-4453636cfcc3-build-1
  namespace: cf-space-4c2ff3db-fcaf-45e0-bae5-0b58f6e20700
spec:
  builder:
    image: <cluster-builder-image>
  cache:
    volume:
      persistentVolumeClaimName: 1fe1df52-f6a8-4065-b335-4453636cfcc3-cache
  env:
  - name: VCAP_SERVICES
    value: '{}'
  resources: {}
  serviceAccountName: kpack-service-account
  source:
    registry:
      image: <source-image-registry>/07843f4e-a6e8-4339-83f0-03d5949a22d3@sha256:0d83fdc9f5e888e20bb3507c670cebd06f1f9bf0f5c5628bd5b6274bbd4ea54c
      imagePullSecrets:
      - name: image-registry-credentials
  tags:
  - <image-registry>/1fe1df52-f6a8-4065-b335-4453636cfcc3
  - <image-registry>/1fe1df52-f6a8-4065-b335-4453636cfcc3:b1.20220510.152550
status:
  conditions:
  - lastTransitionTime: "2022-05-10T15:25:50Z"
    message: resource name may not be empty
    status: "False"
    type: Succeeded
  observedGeneration: 1
  stack: {}
```

Non-working Service Account Example:

```yaml
apiVersion: v1
imagePullSecrets:
- {}
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-05-10T14:56:54Z"
  name: kpack-service-account
  namespace: cf-space-4c2ff3db-fcaf-45e0-bae5-0b58f6e20700
  resourceVersion: "957983"
  uid: 2a3e0ad9-6379-4e4c-adcf-6224a94af6c2
secrets:
- {}
- name: kpack-service-account-token-skp5r
```

Working Service Account Example:

```yaml
apiVersion: v1
imagePullSecrets:
- name: image-registry-credentials
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-05-10T16:51:17Z"
  name: kpack-service-account
  namespace: cf-space-92da6dd9-7acc-44c6-860d-8fbef2b9ee31
  resourceVersion: "1067148"
  uid: 05d4cde7-ff83-48dc-b450-d412e8103823
secrets:
- name: image-registry-credentials
- name: kpack-service-account-token-jds5x
```

**Comment by matthewmcnew** [comment]
I think ideally we would ignore the empty local object reference and proceed with the other secrets on the service account.

**Comment by tcdowney** [comment]
@matthewmcnew I attempted ignoring the invalid object refs, but it just pushed the error deeper and builds started failing with this error:

```
status:
  conditions:
  - lastTransitionTime: "2022-08-19T19:33:19Z"
    message: 'unable to create builder image keychain: resource name may not be empty'
    status: "False"
    type: Succeeded
  observedGeneration: 1
  stack: {}
```

Ignoring the refs turned into a game of whack-a-mole  and I eventually reached some `go-containerregistry` that would need changed:

https://github.com/google/go-containerregistry/blob/2859a0d0d7fab033f90215eecb7cc12fc02e40dd/pkg/authn/kubernetes/keychain.go#L64-L72

I also found that although Kubernetes lets you create `ServiceAccounts` like this, they're pretty invalid (you can't easily [edit them anymore](https://github.com/kubernetes/kubernetes/issues/98963)) so I feel that just raising a more helpful error here feels suitable. I am going to submit a PR that does that for consideration.
