### ISSUE TITLE
I would like to provide my own volume mounts to canonical global cache locations for popular languages

### ISSUE THREAD

**Issue by voor** [pivotal/kpack#978]
I use lots of different language buildpacks, but predominantly Java and JavaScript.  Both have fairly well known caching locations (`~/.m2`, `~/.gradle`, `node_modules`, etc.) and I would like to have a way to pass a PVC that has those necessary subpaths.

My use case is that if I'm already doing some heavy lifting in another Kubernetes native construct, like Tekton, then I already have a Volume that has a `~/.m2` directory inside of it, if I could pass that over to the Java buildpack I can share a lot of caching, and potentially speed up the supply chain.

So something like this:

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: developer-defined-tekton-pipeline
  labels:
    apps.tanzu.vmware.com/pipeline: test
spec:
  params:
    - name: source-url
    - name: source-revision
  workspaces:
    - name: cache
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
      workspaces:
        - workspace: cache
          name: cache
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
        workspaces:
          - name: cache
            optional: true
        steps:
          - name: test
            image: mygradlecontainer
            script: |-
              set -ex

              if [ "$(workspaces.cache.bound)" == "true" ] ; then
                rm -rf ~/.m2 ~/.gradle
                mkdir -p $(workspaces.cache.path)/.m2 $(workspaces.cache.path)/.gradle
                ln -fs $(workspaces.cache.path)/.m2 ~/.m2
                ln -fs $(workspaces.cache.path)/.gradle ~/.gradle
              fi

              cd `mktemp -d`

              wget -qO- $(params.source-url) | tar xvz
              ./gradlew test
```

Where cache is effectively:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"
```

Can be shared by both kpack and Tekton.
